### ISSUE TITLE
Adding more CLI Flags

### ISSUE THREAD

**Issue by jdillard** [UltimateDogg/yang2swagger-generator-old#2]
First off, I think this tool is great, but I wanted to leave feedback that I think could make it an even better tool so that I, or someone else, could pick the ideas up at a later date.

After messing around with it to generate RESTCONF documentation, these are the flags I wish it had:

`-api-version <string> (default: "1.0")`

Currently, when using the CLI, the version number has to be manually added in order to convert to OpenAPI 3.0.

`-format <enum> (default: yaml) (options: json, yaml)`

Some other tools that digest swagger prefer JSON.

`-version`

See what version of yang2swagger is running.

**Comment by UltimateDogg** [comment]
Hi, i forked and tweaked this from a project on bitbucket (https://bitbucket.org/cmurch/yang2swagger-generator) so almost all credit to them :) 

I did add those params to the maven version but i dont use the cli version so i hadnt really thought of CLI. I can look at adding it but i have mostly been working on enhancing an existing plugin in netconf (opendaylight project) using lessons learned from this generator and getting that upstreamed there as i think more eyes will be on that than a solo tool such as this.

**Comment by jdillard** [comment]
Ah, nice!

We are more interested in converting yang to swagger for the RESTCONF side of things so that we can use various out-of-band OpenAPI tools and **yang2swagger** seems to provide the most complete conversion from the convertors we've tried. I currently have **yang2swagger** in a docker container and just run yang files through the CLI to spit out swagger files, so that is why we are interested in the CLI tooling here.

If we submitted PRs that piggybacked on your work and improved the CLI would you be interested in merging them? If not, that's okay.

**Comment by UltimateDogg** [comment]
This issue was moved to UltimateDogg/yang2swagger-generator#1

**Comment by UltimateDogg** [comment]
i found out one of the guys from that repo has a repo on github, so incase they want to get changes back into theirs i forked it, merged everything and will remove this eventually.

**Comment by jdillard** [comment]
awesome :)
